baseURL = 'https://georgecodes.githubio/fakeid'
languageCode = 'en-gb'
title = 'Fake ID Documentation'
theme = "relearn"

[params]
[[params.themeVariant]]
identifier = 'zen-light'
name = 'Light'

[[params.themeVariant]]
identifier = 'zen-dark'
name = 'Dark'

[[params.themeVariant]]
identifier = 'neon'
name = 'Go on, go neon'

ordersectionsby = "weight"
collapsibleMenu = true
alwaysopen = ""