name: Build and publish everything on merge

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"

jobs:
  test-fakeid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Run tests
        run: ./mvnw clean test

  publish-fakeid-lib:
    runs-on: ubuntu-latest
    needs: [test-fakeid]
    if: "!contains(github.event.head_commit.message, '[NOPUBLISH]')"
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Publish fakeid library
        run: ./mvnw deploy -s settings.xml -D skipTests
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

